//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentInfinum
{
    using System;
    using System.Collections.Generic;
    
    public partial class contacts
    {
        public contacts()
        {
            this.phonenumbers = new HashSet<phonenumbers>();
        }
    
        public string name { get; set; }
        public System.DateTime birthdate { get; set; }
        public string address { get; set; }
    
        public virtual ICollection<phonenumbers> phonenumbers { get; set; }
    }
}
